# inceptionV3 preprocessing 

In [1]:
import tensorflow as tf
from tensorflow.contrib.slim import nets
slim = tf.contrib.slim
from PIL import Image 
import numpy as np
from preprocessing import inception_preprocessing

In [2]:
inputs = tf.placeholder("float32", shape=[None, None, 3], name="inputs")
preprocess_inputs = inception_preprocessing.preprocess_image(inputs, 299, 299, is_training=False)
preprocess_inputs = tf.expand_dims(preprocess_inputs, 0)
with slim.arg_scope(nets.inception.inception_v3_arg_scope()):
    net, endpoints = nets.inception.inception_v3(preprocess_inputs, num_classes=1001, is_training=False)
prob = tf.nn.softmax(net)

In [3]:
sess = tf.InteractiveSession()
saver = tf.train.Saver()
saver.restore(sess, "inception_v3.ckpt")

INFO:tensorflow:Restoring parameters from inception_v3.ckpt


In [8]:
im = Image.open("1.jpg")
im = np.array(im, dtype=np.float32) / 255

In [9]:
t = sess.run(endpoints["Predictions"], feed_dict={inputs:im})
# t = sess.run(prob, feed_dict={inputs:im})

In [10]:
np.where(t==np.max(t))

(array([0], dtype=int64), array([387], dtype=int64))

In [11]:
t[0][387]

0.85363925

# Keras Propressing for InceptionV3

In [14]:
import keras
from keras.preprocessing import image
from keras.applications.inception_v3 import InceptionV3, preprocess_input, decode_predictions
import numpy as np

Using TensorFlow backend.


In [15]:
model = InceptionV3(weights=None)
model.load_weights('inception_v3_weights_tf_dim_ordering_tf_kernels.h5')

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [19]:
im = image.load_img("1.jpg", target_size=(299,299))
im = image.img_to_array(im)
im = np.expand_dims(im, axis=0)
im = preprocess_input(im)

In [20]:
preds = model.predict(im)
print('Predicted:', decode_predictions(preds, top=3)[0])

Predicted: [('n02504458', 'African_elephant', 0.97499096), ('n01871265', 'tusker', 0.016361132), ('n02504013', 'Indian_elephant', 0.0023547967)]


In [21]:
np.max(preds[0])

0.97499096

### tensorflow

In [1]:
import os
from tensorflow.python import pywrap_tensorflow

reader = pywrap_tensorflow.NewCheckpointReader("resnet_v1_50.ckpt") #tf.train.NewCheckpointReader
var_to_shape_map = reader.get_variable_to_shape_map()
for key in var_to_shape_map:
	print("tensor_name: ", key)
	# print(reader.get_tensor(k

tensor_name:  resnet_v1_50/block1/unit_2/bottleneck_v1/conv3/BatchNorm/gamma
tensor_name:  resnet_v1_50/block4/unit_1/bottleneck_v1/conv1/weights
tensor_name:  resnet_v1_50/block1/unit_2/bottleneck_v1/conv2/BatchNorm/moving_mean
tensor_name:  resnet_v1_50/block1/unit_2/bottleneck_v1/conv1/BatchNorm/gamma
tensor_name:  resnet_v1_50/block4/unit_3/bottleneck_v1/conv1/BatchNorm/moving_variance
tensor_name:  resnet_v1_50/block3/unit_5/bottleneck_v1/conv2/BatchNorm/gamma
tensor_name:  resnet_v1_50/block2/unit_2/bottleneck_v1/conv2/BatchNorm/moving_mean
tensor_name:  resnet_v1_50/logits/weights
tensor_name:  resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/weights
tensor_name:  resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/BatchNorm/gamma
tensor_name:  resnet_v1_50/block1/unit_2/bottleneck_v1/conv3/BatchNorm/moving_variance
tensor_name:  resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/BatchNorm/beta
tensor_name:  resnet_v1_50/block3/unit_2/bottleneck_v1/conv3/BatchNorm/moving_variance
tensor_na

In [3]:
conv1 = reader.get_tensor("resnet_v1_50/conv1/weights")

In [4]:
conv1.shape

(7, 7, 3, 64)

In [6]:
conv1[:,:,:,0]

array([[[-2.4409075e-03,  5.8682780e-03,  2.8252628e-02],
        [ 1.9045383e-02,  1.8755430e-02,  1.8187232e-02],
        [ 2.1795981e-02,  3.6142137e-02,  1.5884932e-02],
        [-3.3809561e-03,  1.7154936e-02,  2.4200524e-03],
        [-7.6958969e-02, -9.3557894e-02, -5.3015325e-02],
        [-7.1311310e-02, -1.2410009e-01, -4.7355831e-02],
        [ 1.4394077e-02, -2.6807901e-02,  1.8542951e-02]],

       [[ 3.7047156e-04, -7.6879463e-03,  7.9900930e-03],
        [ 2.9127423e-02,  2.4296619e-02,  2.4885667e-02],
        [ 1.1718027e-01,  1.4944476e-01,  7.6726004e-02],
        [ 1.5079568e-01,  2.1562344e-01,  9.0264283e-02],
        [-9.3867844e-03,  1.3388847e-02, -1.8915119e-02],
        [-1.3021459e-01, -1.7687228e-01, -7.9356186e-02],
        [-7.9232596e-02, -1.2294715e-01, -1.5361722e-02]],

       [[-3.3404842e-02, -7.4660495e-02, -2.7473288e-02],
        [-8.8074416e-02, -1.5249401e-01, -6.5753512e-02],
        [ 8.0531552e-02,  6.1024245e-02,  1.9992139e-02],
        [ 

### keras

In [2]:
import h5py
f = h5py.File('resnet50_weights_tf_dim_ordering_tf_kernels.h5','r')   #打开h5文件 
for key in f.keys(): 
    print(key )
    for subkey in f[key]:
        print(subkey )
#         print(f[key][subkey].value)
        print(f[key][subkey].shape)


activation_1
activation_10
activation_11
activation_12
activation_13
activation_14
activation_15
activation_16
activation_17
activation_18
activation_19
activation_2
activation_20
activation_21
activation_22
activation_23
activation_24
activation_25
activation_26
activation_27
activation_28
activation_29
activation_3
activation_30
activation_31
activation_32
activation_33
activation_34
activation_35
activation_36
activation_37
activation_38
activation_39
activation_4
activation_40
activation_41
activation_42
activation_43
activation_44
activation_45
activation_46
activation_47
activation_48
activation_49
activation_5
activation_6
activation_7
activation_8
activation_9
avg_pool
bn2a_branch1
bn2a_branch1_beta:0
(256,)
bn2a_branch1_gamma:0
(256,)
bn2a_branch1_running_mean:0
(256,)
bn2a_branch1_running_std:0
(256,)
bn2a_branch2a
bn2a_branch2a_beta:0
(64,)
bn2a_branch2a_gamma:0
(64,)
bn2a_branch2a_running_mean:0
(64,)
bn2a_branch2a_running_std:0
(64,)
bn2a_branch2b
bn2a_branch2b_beta:0
(64,

(2048,)
res5b_branch2a
res5b_branch2a_W:0
(1, 1, 2048, 512)
res5b_branch2a_b:0
(512,)
res5b_branch2b
res5b_branch2b_W:0
(3, 3, 512, 512)
res5b_branch2b_b:0
(512,)
res5b_branch2c
res5b_branch2c_W:0
(1, 1, 512, 2048)
res5b_branch2c_b:0
(2048,)
res5c_branch2a
res5c_branch2a_W:0
(1, 1, 2048, 512)
res5c_branch2a_b:0
(512,)
res5c_branch2b
res5c_branch2b_W:0
(3, 3, 512, 512)
res5c_branch2b_b:0
(512,)
res5c_branch2c
res5c_branch2c_W:0
(1, 1, 512, 2048)
res5c_branch2c_b:0
(2048,)
zeropadding2d_1


In [3]:
conv1 = f["conv1"]["conv1_W:0"]
conv1.value[:,:,::-1,0]#B

array([[[-2.4409075e-03,  5.8682780e-03,  2.8252628e-02],
        [ 1.9045383e-02,  1.8755430e-02,  1.8187232e-02],
        [ 2.1795981e-02,  3.6142137e-02,  1.5884932e-02],
        [-3.3809561e-03,  1.7154936e-02,  2.4200524e-03],
        [-7.6958969e-02, -9.3557894e-02, -5.3015325e-02],
        [-7.1311310e-02, -1.2410009e-01, -4.7355831e-02],
        [ 1.4394077e-02, -2.6807901e-02,  1.8542951e-02]],

       [[ 3.7047156e-04, -7.6879463e-03,  7.9900930e-03],
        [ 2.9127423e-02,  2.4296619e-02,  2.4885667e-02],
        [ 1.1718027e-01,  1.4944476e-01,  7.6726004e-02],
        [ 1.5079568e-01,  2.1562344e-01,  9.0264283e-02],
        [-9.3867844e-03,  1.3388847e-02, -1.8915119e-02],
        [-1.3021459e-01, -1.7687228e-01, -7.9356186e-02],
        [-7.9232596e-02, -1.2294715e-01, -1.5361722e-02]],

       [[-3.3404842e-02, -7.4660495e-02, -2.7473288e-02],
        [-8.8074416e-02, -1.5249401e-01, -6.5753512e-02],
        [ 8.0531552e-02,  6.1024245e-02,  1.9992139e-02],
        [ 